### PR TITLE
Unify server binaries

### PR DESCRIPTION
**Pull request by ekrembal**

### CODE REVIEW

**Comment by ceyhunsen** [comment]
Adding how to use this features to readme can help. Do we want to outsiders to use these binaries?

**Review by ceyhunsen — COMMENTED** [review]
Works as expected. But code looks weird.

In this context we don't need small performance benefits while starting servers. Because of this, we can actually use CLI flags passed to binary itself. This will result:

- One binary to every use case
- Binaries won't get big because actual application code is the smallest part of our binaries
- We won't be able to limit user to do one thing and one thing only; Users are free to run which server they want

With CLI flags, this can be the usage (which is clearer for me):

```bash
cargo run --verifier-server --operator-server --aggregator-server
```

**Comment by ozankaymak** [comment]
IMO @ceyhunsen is right; however, README.md should itself completely change because a lot of things changed since the design was changed. I think it deserves to be a seperate issue. @ekrembal ?

**Review by ozankaymak — APPROVED** [review]

**Comment by ekrembal** [comment]
Yes, will update README but not first priority. I think using a single binary is not that good and this implementation is simpler

**Review by ceyhunsen — APPROVED** [review]

**Pull request merged**
